"""Centralized UI string constants for the GUI viewer."""

from __future__ import annotations

WINDOW_TITLE = "FastFileViewer"
WINDOW_TITLE_OPEN_FMT = "FastFileViewer - {path}"

MENU_FILE = "&File"
ACTION_OPEN = "Open file…"
ACTION_QUIT = "Quit"
ACTION_COMMAND_PALETTE = "Command palette…"
ACTION_OPEN_HISTORY = "Open file from recent / history…"

# Command palette / history picker
PALETTE_TITLE = "Command palette"
PALETTE_PLACEHOLDER = "Type a command…"
HISTORY_TITLE = "Open file from recent / history"
HISTORY_PLACEHOLDER = "Filter recent documents…"
FOLDER_HISTORY_TITLE = "Open folder from recent / history"
FOLDER_HISTORY_PLACEHOLDER = "Filter recent folders…"
SHORTCUTS_TITLE = "Keyboard and mouse controls"
SHORTCUTS_PLACEHOLDER = "Filter controls…"
SHORTCUT_ROW_FMT = "{chord}  —  {title}"

# F1 chooser: pick which controls to view/edit
CHOOSE_KEYBOARD_LABEL = "Keyboard shortcuts…"
CHOOSE_MOUSE_LABEL = "Mouse controls"
MOUSE_CONTROLS_TITLE = "Mouse controls"
MOUSE_CONTROLS_PLACEHOLDER = "Filter controls…"

# Mouse controls (shown in the controls dialog; not bound to commands)
MOUSE_WHEEL = "Wheel"
MOUSE_WHEEL_DESC = "Scroll page · flip at edge"
MOUSE_SHIFT_WHEEL = "Shift+Wheel"
MOUSE_SHIFT_WHEEL_DESC = "Scroll horizontally"
MOUSE_CTRL_WHEEL = "Ctrl+Wheel"
MOUSE_CTRL_WHEEL_DESC = "Previous / next page"

# Command titles (shown in the palette and menus)
CMD_OPEN = "Open file…"
CMD_OPEN_DIR = "Open folder…"
CMD_OPEN_HISTORY = "Open file from recent / history…"
CMD_OPEN_FOLDER_HISTORY = "Open folder from recent / history…"
CMD_NEXT_FILE = "Next file in directory"
CMD_PREV_FILE = "Previous file in directory"
CMD_CLOSE_DOC = "Close current document"
CMD_EXIT = "Exit"
CMD_PREV_PAGE = "Previous page"
CMD_NEXT_PAGE = "Next page"
CMD_FIRST_PAGE = "First page"
CMD_LAST_PAGE = "Last page"
CMD_ZOOM_FIT = "Zoom to fit"
CMD_ZOOM_ACTUAL = "Zoom 100%"
CMD_ZOOM_IN = "Zoom in 10%"
CMD_ZOOM_OUT = "Zoom out 10%"
CMD_SWAP = "Swap 2 pages"
CMD_DELETE_PAGE = "Delete current page"
CMD_DELETE_RANGE = "Delete page range…"
CMD_INSERT_PAGE = "Insert pages (PDF or image)…"
CMD_EXTRACT_PAGE = "Extract current page to file…"
CMD_MERGE_FOLDER = "Merge folder…"
CMD_ROTATE_LEFT = "Rotate page 90° left"
CMD_ROTATE_RIGHT = "Rotate page 90° right"
CMD_ROTATE_180 = "Rotate page 180°"
CMD_FLIP_HORIZONTAL = "Flip page horizontally"
CMD_FLIP_VERTICAL = "Flip page vertically"
CMD_MOVE_NEXT = "Move page to next position"
CMD_MOVE_PREV = "Move page to previous position"
CMD_MOVE_FIRST = "Move page to first"
CMD_MOVE_LAST = "Move page to last"
CMD_SAVE = "Save changes to original file"
CMD_PRINT = "Print…"
CMD_SHOW_SHORTCUTS = "Help: Show keyboard and mouse controls"
CMD_COMMAND_PALETTE = "Command palette"
CMD_CONFIGURE_SHORTCUTS = "Configure keyboard shortcuts…"
CMD_EDIT_MODE = "Toggle edit mode"
CMD_ADD_FIELD = "Add text field"
CMD_ADD_IMAGE = "Add image…"
CMD_IMAGE_SCALE = "Image: scale…"
CMD_IMAGE_DELETE = "Image: delete"
CMD_SELECT_NEXT = "Select next editable element"
CMD_SELECT_PREV = "Select previous editable element"
CMD_DELETE_FIELD = "Delete selected field"
CMD_EXPORT_TEXT = "Export to PDF (text + images)"
CMD_DELETE_SAVED_FIELDS = "Delete saved text fields for this document"
CMD_REMEMBERED_SETTINGS = "Remembered settings…"

# Export-text flow (overwrite original vs. write a new flattened file)
CONFIRM_EXPORT_TITLE = "Export text"
CONFIRM_EXPORT_OVERWRITE = (
    "Overwrite the original PDF?\n\n"
    "Yes: flatten the text into the original and remove the editable text data "
    "(the text can no longer be edited).\n"
    "No: export to a new file; the original stays editable."
)
DIALOG_EXPORT_NAME_TITLE = "Export to new file"
PROMPT_EXPORT_NAME = "New file name:"
MSG_TEXT_EXPORTED_FMT = "exported text to: {name}"
MSG_NO_TEXT_TO_EXPORT = "No text fields to export."

CONFIRM_DELETE_SAVED_FIELDS = "Delete all saved text fields for this document?"
MSG_SAVED_FIELDS_DELETED_FMT = "deleted saved text fields for: {name}"
LABEL_HISTORY_EMPTY = "No recent documents"

# Text-field placement chooser (where a new field lands)
PLACEMENT_TITLE = "Place new text field"
PLACEMENT_PLACEHOLDER = "Choose where to add the field…"
PLACEMENT_TOP_LEFT = "Top left of page"
PLACEMENT_PAGE_CENTER = "Center of page"
PLACEMENT_VIEW_CENTER = "Center of current view"
PLACEMENT_CUSTOM = "Custom position…"
PLACEMENT_HINT = "Click or arrows + Enter to place • Esc to cancel"

# Color picker
COLOR_DIALOG_TITLE = "Pick a color"
COLOR_PLACEHOLDER = "Type a hex (#ff8800) or name (white)…"

# Search
CMD_SEARCH_PDF = "Search document text…"
CMD_SEARCH_FIELDS = "Search text fields…"
CMD_CLEAR_HIGHLIGHTS = "Clear search highlights"
SEARCH_PDF_TITLE = "Search document text"
SEARCH_FIELDS_TITLE = "Search text fields"
SEARCH_PLACEHOLDER = "Type at least 3 characters…"
SEARCH_RESULT_FMT = "Page {page}: {snippet}"
SEARCH_RESULT_NO_SNIPPET = "(match)"

# Active-field commands (shown only while a field is selected)
CMD_FIELD_CHANGE_TEXT = "Field: Change / Edit text"
CMD_FIELD_FONT_SIZE = "Field: font size…"
CMD_FIELD_FONT_FAMILY = "Field: font family…"
CMD_FIELD_TEXT_COLOR = "Field: text color…"
CMD_FIELD_BG_COLOR = "Field: background color…"
CMD_FIELD_TOGGLE_BOLD = "Field: toggle bold"
CMD_FIELD_TOGGLE_ITALIC = "Field: toggle italic"
CMD_FIELD_DELETE = "Field: delete"

FONT_DIALOG_TITLE = "Pick a font"
FONT_PLACEHOLDER = "Type a font name…"
DIALOG_FIELD_TEXT_TITLE = "Change field text"
PROMPT_FIELD_TEXT = "Text:"
HINT_CTRL_ENTER = "Press Ctrl+Enter to apply, Esc to cancel."
DIALOG_FIELD_SIZE_TITLE = "Field font size"
PROMPT_FIELD_SIZE = "Size (px):"

# Image overlay
DIALOG_ADD_IMAGE_TITLE = "Choose image to place"
CONFIRM_IMAGE_COPY_TITLE = "Add image"
CONFIRM_IMAGE_COPY_TEXT = (
    "Copy the image into an 'assets' folder next to the PDF?\n\n"
    "Yes: copy into assets/ (keeps the PDF self-contained).\n"
    "No: reference the original file at its current location."
)
DIALOG_IMAGE_SCALE_TITLE = "Image scale"
PROMPT_IMAGE_SCALE = "Scale (× of original size):"
MSG_NO_IMAGE_SELECTED = "No image selected."

# Keyboard-shortcut configuration
CONFIGURE_SHORTCUTS_TITLE = "Configure keyboard shortcuts"
CONFIGURE_SHORTCUTS_PLACEHOLDER = "Search a command to bind, Del to clear…"
CAPTURE_TITLE = "Set shortcut"
CAPTURE_PROMPT_FMT = "Press a shortcut for:\n{title}"
CAPTURE_DETECTED_FMT = "Detected: {chord}\n\nEnter to confirm · Esc to cancel"
CAPTURE_WAITING = "Press your shortcut…"
CONFIRM_REASSIGN_TITLE = "Reassign shortcut"
CONFIRM_REASSIGN_FMT = "{chord} is bound to “{current}”.\nReassign it to “{target}”?"
CONFIRM_ADD_OR_REPLACE_TITLE = "Add or replace shortcut"
CONFIRM_ADD_OR_REPLACE_FMT = (
    "“{title}” already has {chords}.\nAdd {chord} as well, or replace the existing one(s)?"
)
CONFIRM_CLEAR_SHORTCUT_TITLE = "Clear shortcut"
CONFIRM_CLEAR_SHORTCUT_FMT = "Remove the shortcut(s) {chords} from “{title}”?"
DELETE_SHORTCUT_TITLE_FMT = "Delete which shortcut for “{title}”?"
DELETE_SHORTCUT_PLACEHOLDER = "Choose a shortcut to remove…"
DELETE_ALL_SHORTCUTS = "All shortcuts"
MSG_SHORTCUT_SET_FMT = "bound {chord} to “{title}”"
MSG_SHORTCUT_STOLEN_FMT = "bound {chord} to “{title}” (removed from “{stolen}”)"
MSG_SHORTCUT_CLEARED_FMT = "cleared shortcut(s) for “{title}”"
MSG_SHORTCUT_CHORD_REMOVED_FMT = "removed {chord} from “{title}”"
MSG_SHORTCUT_NONE_TO_CLEAR_FMT = "“{title}” has no shortcut to clear"

# Remembered-settings management
REMEMBERED_TITLE = "Remembered settings"
REMEMBERED_PLACEHOLDER = "Choose a setting to reset…"
REMEMBERED_CLEAR_ALL = "Clear ALL remembered settings"
MSG_REMEMBERED_RESET_FMT = "reset: {name}"
MSG_REMEMBERED_CLEARED = "cleared all remembered settings"

BTN_PREV = "◀ Prev"
BTN_NEXT = "Next ▶"
BTN_SWAP = "Swap 2 pages"
BTN_DELETE_PAGE = "Delete current page"
BTN_DELETE_RANGE = "Delete range…"
BTN_INSERT_PAGE = "Insert…"
BTN_EXTRACT_PAGE = "Extract page…"
BTN_MERGE_FOLDER = "Merge folder…"

CMD_RENAME_FILE = "Rename file…"
CMD_TOGGLE_MENU = "Toggle menu bar"
CMD_TOGGLE_TOOLBAR = "Toggle toolbar"
CMD_TOGGLE_STATUSBAR = "Toggle status bar"
CMD_TOGGLE_FULLSCREEN = "Toggle fullscreen"

# Animated-GIF playback toggle. Stable label (not state-flipped) so the palette's
# type-to-filter finds it by "play" OR "pause" whatever the current state.
CMD_GIF_TOGGLE = "GIF: play / pause"

# Settings command titles (their dialogs live in app.gui.settings_strings)
CMD_PALETTE_WIDTH = "Palette: width %…"
CMD_PALETTE_HEIGHT = "Palette: height %…"
CMD_PALETTE_FONT = "Palette: font size…"
CMD_PALETTE_OPACITY = "Palette: opacity %…"
CMD_PALETTE_BORDERLESS = "Palette: toggle borderless"
CMD_DIALOG_SIZE = "Dialogs: size %…"
CMD_OUTLINE_WIDTH = "Outline: width…"
CMD_OUTLINE_STYLE = "Outline: type…"
CMD_OUTLINE_COLOR = "Outline: color…"
CMD_TEXT_DARK_MODE = "Text/Markdown: toggle dark mode"
CMD_TEXT_FONT_SIZE = "Text/Markdown: font size…"
CMD_OPEN_FILTER_ALL_FILES = "Open dialog: toggle all files"
CMD_OPEN_FILTER_EXTENSIONS = "Open dialog: file extensions…"
CMD_REUSE_WINDOW = "Single instance: toggle reuse existing window"
CMD_FOCUS_ON_FORWARD = "Single instance: toggle focus window on open"
CMD_SET_DEFAULT_ZOOM = "Set default zoom…"
CMD_REMEMBER_DOC_ZOOM = "Zoom: remember for documents…"
CMD_REMEMBER_DOC_PAGE = "Page: remember for documents…"


DIALOG_RENAME_TITLE = "Rename file"
PROMPT_RENAME = "New file name:"
MSG_RENAMED_FMT = "renamed to: {name}"

BTN_EDIT_MODE = "Edit mode"
BTN_ADD_FIELD = "Add field"
BTN_ADD_IMAGE = "Add image"
BTN_DELETE_FIELD = "Delete field"
BTN_EXPORT_TEXT = "Export"
BTN_TEXT_COLOR = "Text color…"
BTN_BG_COLOR = "Background"
BTN_BOLD = "B"
BTN_ITALIC = "I"
LABEL_FONT = "Font:"
LABEL_SIZE = "Size:"
EDIT_DEFAULT_TEXT = "Text"
DIALOG_TEXT_COLOR_TITLE = "Choose text color"
DIALOG_BG_COLOR_TITLE = "Choose background color"

DIALOG_OPEN_TITLE = "Open file"
DIALOG_OPEN_DIR_TITLE = "Open folder"
DIALOG_INSERT_TITLE = "Choose PDF or image to insert"
DIALOG_EXTRACT_TITLE = "Extract current page to file"
DIALOG_MERGE_TITLE = "Choose folder to merge"
DIALOG_RANGE_TITLE = "Delete page range"
PROMPT_RANGE_START = "Start page (1-based, inclusive):"
PROMPT_RANGE_END = "End page (1-based, inclusive):"
CONFIRM_TITLE = "Confirm"
CONFIRM_DELETE_PAGE_FMT = "Delete page {page} of {total}?"
CONFIRM_UNSAVED_TITLE = "Unsaved changes"
CONFIRM_UNSAVED_TEXT = "Save changes to the original file before closing?"

DIALOG_ERROR_TITLE = "Operation failed"

# Shared dialog button labels (custom confirm / alert / input dialogs)
BTN_OK = "OK"
BTN_CANCEL = "Cancel"
BTN_YES = "Yes"
BTN_NO = "No"
BTN_SAVE = "Save"
BTN_DISCARD = "Discard"
BTN_APPEND = "Add"
BTN_REPLACE = "Replace"

LABEL_NO_DOC = "No document open"
# Shared by the operation bar and the mode footer so both read identically.
LABEL_PAGE_FMT = "Page {current}/{total}"

# Mode footer bar
MODE_REGULAR = "Regular Mode"
MODE_EDIT = "Edit Mode"
FILE_OF_FMT = "File {current}/{total}"
# Bare counter for unpaged formats (images): no "File" word, no page row to
# disambiguate from, so the label stays clean.
FILE_COMPACT_FMT = "{current}/{total}"
ZOOM_FMT = "{percent}%"
MODIFIED_MARKER = "● Modified"
HINT_NO_SIBLING_FILE = "No other file in directory"
HINT_NO_OPENABLE_FILE = "No openable file in this folder"

MSG_NOT_FOUND_FMT = "input file not found: {path}"
MSG_UNSUPPORTED_FORMAT_FMT = "unsupported file type: {name}"
MSG_OPEN_FAILED_FMT = "could not open {name}: {error}"
MSG_BACKUP_FAILED_FMT = "failed to create backup: {error}"
MSG_DONE_FMT = "done: {name}"
MSG_MERGED_FMT = "merged: {path}"
MSG_TEXT_EMBEDDED = "text embedded into the document"
MSG_SIDECAR_LOAD_FAILED_FMT = "could not load saved text fields: {error}"
MSG_SAVED_FMT = "saved changes to: {name}"
MSG_NO_CHANGES = "No unsaved changes."
MSG_NO_DOCUMENT = "No document is open."
