"""Centralized UI string constants for the GUI viewer."""

from __future__ import annotations

WINDOW_TITLE = "pdf-toolkit viewer"

MENU_FILE = "&File"
ACTION_OPEN = "Open PDF…"
ACTION_QUIT = "Quit"
ACTION_COMMAND_PALETTE = "Command palette…"
ACTION_OPEN_HISTORY = "Open from history…"

# Command palette / history picker
PALETTE_TITLE = "Command palette"
PALETTE_PLACEHOLDER = "Type a command…"
HISTORY_TITLE = "Open from history"
HISTORY_PLACEHOLDER = "Filter recent documents…"
SHORTCUTS_TITLE = "Keyboard shortcuts"
SHORTCUTS_PLACEHOLDER = "Filter shortcuts…"
SHORTCUT_ROW_FMT = "{chord}  —  {title}"

# Command titles (shown in the palette and menus)
CMD_OPEN = "Open PDF…"
CMD_OPEN_HISTORY = "Open from history…"
CMD_CLOSE_DOC = "Close current document"
CMD_EXIT = "Exit"
CMD_PREV_PAGE = "Previous page"
CMD_NEXT_PAGE = "Next page"
CMD_FIRST_PAGE = "First page"
CMD_LAST_PAGE = "Last page"
CMD_ZOOM_FIT = "Zoom to fit"
CMD_ZOOM_ACTUAL = "Zoom 100%"
CMD_ZOOM_IN = "Zoom in 10%"
CMD_ZOOM_OUT = "Zoom out 10%"
CMD_SWAP = "Swap 2 pages"
CMD_DELETE_PAGE = "Delete current page"
CMD_DELETE_RANGE = "Delete page range…"
CMD_MERGE_FOLDER = "Merge folder…"
CMD_ROTATE_LEFT = "Rotate page 90° left"
CMD_ROTATE_RIGHT = "Rotate page 90° right"
CMD_ROTATE_180 = "Rotate page 180°"
CMD_MOVE_NEXT = "Move page to next position"
CMD_MOVE_PREV = "Move page to previous position"
CMD_MOVE_FIRST = "Move page to first"
CMD_MOVE_LAST = "Move page to last"
CMD_SAVE = "Save changes to original file"
CMD_SHOW_SHORTCUTS = "Show keyboard shortcuts"
CMD_EDIT_MODE = "Toggle text edit mode"
CMD_ADD_FIELD = "Add text field"
CMD_DELETE_FIELD = "Delete selected field"
CMD_EXPORT_TEXT = "Export text to PDF"
CMD_DELETE_SAVED_FIELDS = "Delete saved text fields for this document"

CONFIRM_DELETE_SAVED_FIELDS = "Delete all saved text fields for this document?"
LABEL_HISTORY_EMPTY = "No recent documents"

# Colour picker
COLOR_DIALOG_TITLE = "Pick a colour"
COLOR_PLACEHOLDER = "Type a hex (#ff8800) or name (white)…"

# Search
CMD_SEARCH_PDF = "Search PDF text…"
CMD_SEARCH_FIELDS = "Search text fields…"
CMD_CLEAR_HIGHLIGHTS = "Clear search highlights"
SEARCH_PDF_TITLE = "Search PDF text"
SEARCH_FIELDS_TITLE = "Search text fields"
SEARCH_PLACEHOLDER = "Type at least 3 characters…"
SEARCH_RESULT_FMT = "Page {page}: {snippet}"
SEARCH_RESULT_NO_SNIPPET = "(match)"

# Active-field commands (shown only while a field is selected)
CMD_FIELD_CHANGE_TEXT = "Field: change text…"
CMD_FIELD_FONT_SIZE = "Field: font size…"
CMD_FIELD_FONT_FAMILY = "Field: font family…"
CMD_FIELD_TEXT_COLOR = "Field: text colour…"
CMD_FIELD_BG_COLOR = "Field: background colour…"
CMD_FIELD_TOGGLE_BOLD = "Field: toggle bold"
CMD_FIELD_TOGGLE_ITALIC = "Field: toggle italic"
CMD_FIELD_DELETE = "Field: delete"

FONT_DIALOG_TITLE = "Pick a font"
FONT_PLACEHOLDER = "Type a font name…"
DIALOG_FIELD_TEXT_TITLE = "Change field text"
PROMPT_FIELD_TEXT = "Text:"
HINT_CTRL_ENTER = "Press Ctrl+Enter to apply, Esc to cancel."
DIALOG_FIELD_SIZE_TITLE = "Field font size"
PROMPT_FIELD_SIZE = "Size (px):"

BTN_PREV = "◀ Prev"
BTN_NEXT = "Next ▶"
BTN_SWAP = "Swap 2 pages"
BTN_DELETE_PAGE = "Delete current page"
BTN_DELETE_RANGE = "Delete range…"
BTN_MERGE_FOLDER = "Merge folder…"

CMD_RENAME_FILE = "Rename file…"
CMD_TOGGLE_MENU = "Toggle menu bar"
CMD_TOGGLE_TOOLBAR = "Toggle toolbar"

# Command-palette appearance settings
CMD_PALETTE_WIDTH = "Palette: width %…"
CMD_PALETTE_HEIGHT = "Palette: height %…"
CMD_PALETTE_FONT = "Palette: font size…"
CMD_PALETTE_OPACITY = "Palette: opacity %…"
CMD_PALETTE_BORDERLESS = "Palette: toggle borderless"
DIALOG_PALETTE_WIDTH_TITLE = "Palette width"
DIALOG_PALETTE_HEIGHT_TITLE = "Palette height"
DIALOG_PALETTE_FONT_TITLE = "Palette font size"
DIALOG_PALETTE_OPACITY_TITLE = "Palette opacity"
PROMPT_PALETTE_WIDTH = "Width (% of window):"
PROMPT_PALETTE_HEIGHT = "Height (% of window):"
PROMPT_PALETTE_FONT = "Font size (pt, 0 = default):"
PROMPT_PALETTE_OPACITY = "Opacity (%):"
DIALOG_RENAME_TITLE = "Rename file"
PROMPT_RENAME = "New file name:"
MSG_RENAMED_FMT = "renamed to: {name}"

BTN_EDIT_MODE = "Edit text"
BTN_ADD_FIELD = "Add field"
BTN_DELETE_FIELD = "Delete field"
BTN_EXPORT_TEXT = "Export text"
BTN_TEXT_COLOR = "Text colour…"
BTN_BG_COLOR = "Background"
BTN_BOLD = "B"
BTN_ITALIC = "I"
LABEL_FONT = "Font:"
LABEL_SIZE = "Size:"
EDIT_DEFAULT_TEXT = "Text"
DIALOG_TEXT_COLOR_TITLE = "Choose text colour"
DIALOG_BG_COLOR_TITLE = "Choose background colour"

FILE_FILTER_PDF = "PDF files (*.pdf)"
DIALOG_OPEN_TITLE = "Open PDF"
DIALOG_MERGE_TITLE = "Choose folder to merge"
DIALOG_RANGE_TITLE = "Delete page range"
PROMPT_RANGE_START = "Start page (1-based, inclusive):"
PROMPT_RANGE_END = "End page (1-based, inclusive):"
CONFIRM_TITLE = "Confirm"
CONFIRM_DELETE_PAGE_FMT = "Delete page {page} of {total}?"
CONFIRM_UNSAVED_TITLE = "Unsaved changes"
CONFIRM_UNSAVED_TEXT = "Save changes to the original file before closing?"

DIALOG_ERROR_TITLE = "Operation failed"
DIALOG_SUCCESS_TITLE = "Done"

LABEL_NO_DOC = "No PDF open"
LABEL_PAGE_FMT = "Page {current} / {total}"

# Mode footer bar
MODE_REGULAR = "Regular Mode"
MODE_EDIT_TEXT = "Edit Text Mode"
PAGE_OF_FMT = "{current}/{total}"
MODIFIED_MARKER = "● Modified"

MSG_NOT_FOUND_FMT = "input file not found: {path}"
MSG_BACKUP_FAILED_FMT = "failed to create backup: {error}"
MSG_DONE_FMT = "done: {name}"
MSG_MERGED_FMT = "merged: {path}"
MSG_TEXT_EMBEDDED = "text embedded into the document"
MSG_SIDECAR_LOAD_FAILED_FMT = "could not load saved text fields: {error}"
MSG_SAVED_FMT = "saved changes to: {name}"
MSG_NO_CHANGES = "No unsaved changes."
MSG_NO_DOCUMENT = "No document is open."
